export const exStudents = [
  // Similar structure with additional certificate data
  {
    id: 1,
    lcNo: "650",
    enrollNo: "1890",
    name: "JOSHI ANANYA PRAKASH",
    stdFromLeave: "STD 10TH (TENTH) SINCE JUNE 2022",
    stdClass: "STD X-A",
    reasonOfLeaving: "GRADUATION",
    remark: "PASSED STD 10TH IN APRIL 2023",
    leftDate: "30-04-2023",
    issueDate: "15-05-2023",
    // Additional data for certificate
    studentIdNo: "27015273611156140029",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "650",
    generalRegisterNo: "1659",
    uidAadharCardNo: "738304278349",
    fatherName: "PRAKASH",
    motherName: "DEEPA",
    nationality: "INDIAN",
    motherTongue: "MARATHI",
    religion: "HINDU",
    caste: "BRAHMIN",
    subCaste: "",
    placeOfBirth: "PUNE",
    district: "PUNE",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "05-05-2008",
    dateOfBirthInWords: "Fifth May Two Thousand Eight",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "9TH (NINTH)",
    dateOfAdmission: "10-06-2021",
    progressInStudies: "EXCELLENT",
    conduct: "EXCELLENT",
    standardStudying: "STD 10TH (TENTH) SINCE JUNE 2022",
  },
  // Other ex-students...
];
