export const lcStudents = [
  {
    id: 1,
    lcNo: "826",
    enrollNo: "1446",
    name: "MIRZA SHABBO JAKIR MIRZA",
    stdFromLeave: "STD 10TH (TENTH) SINCE JUNE 2024",
    stdClass: "STD X-A",
    reasonOfLeaving: "GUARDIAN WISH",
    remark: "PASSED STD 9TH IN APRIL 2024",
    leftDate: "30-08-2024",
    issueDate: "30-08-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140022",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "826",
    generalRegisterNo: "1652",
    uidAadharCardNo: "738304278342",
    fatherName: "JAKIR",
    motherName: "PARVIN BEGUM",
    nationality: "INDIAN",
    motherTongue: "HINDI",
    religion: "MUSLIM",
    caste: "MUSLIM",
    subCaste: "",
    placeOfBirth: "BOISAR (EAST) THANE",
    district: "",
    state: "",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "24-06-2009",
    dateOfBirthInWords: "Twenty Fourth June Two Thousand Nine",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "8TH (EIGHTH)",
    dateOfAdmission: "15-06-2022",
    progressInStudies: "SATISFACTORY",
    conduct: "GOOD",
    standardStudying: "STD 10TH (TENTH) SINCE JUNE 2024",
  },
  {
    id: 2,
    lcNo: "825",
    enrollNo: "3105",
    name: "YADAV KRISHNA ARUN KUMAR",
    stdFromLeave: "STD 9TH (NINETH) SINCE JUNE 2024",
    stdClass: "STD VIII-A",
    reasonOfLeaving: "CONTINUOUS ABSENT SINCE JUNE 2024",
    remark: "PASSED STD 8TH IN APRIL 2024",
    leftDate: "14-08-2024",
    issueDate: "14-08-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140023",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "825",
    generalRegisterNo: "1653",
    uidAadharCardNo: "738304278343",
    fatherName: "ARUN KUMAR",
    motherName: "SUNITA DEVI",
    nationality: "INDIAN",
    motherTongue: "HINDI",
    religion: "HINDU",
    caste: "OBC",
    subCaste: "",
    placeOfBirth: "MUMBAI",
    district: "MUMBAI",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "15-08-2010",
    dateOfBirthInWords: "Fifteenth August Two Thousand Ten",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "8TH (EIGHTH)",
    dateOfAdmission: "20-06-2022",
    progressInStudies: "GOOD",
    conduct: "EXCELLENT",
    standardStudying: "STD 9TH (NINETH) SINCE JUNE 2024",
  },
  // Other students with similar additional data...
  {
    id: 3,
    lcNo: "822",
    enrollNo: "3319",
    name: "ANSARI SHANA PARVEEN SIRAJ",
    stdFromLeave: "STD 8TH (EIGHTH) SINCE JUNE 2023",
    stdClass: "STD IX-A",
    reasonOfLeaving: "GUARDIAN WISH",
    remark: "PASSED STD 8TH IN APRIL 2024",
    leftDate: "02-05-2024",
    issueDate: "02-05-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140024",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "822",
    generalRegisterNo: "1654",
    uidAadharCardNo: "738304278344",
    fatherName: "SIRAJ",
    motherName: "FATIMA",
    nationality: "INDIAN",
    motherTongue: "URDU",
    religion: "MUSLIM",
    caste: "MUSLIM",
    subCaste: "",
    placeOfBirth: "THANE",
    district: "THANE",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "10-05-2011",
    dateOfBirthInWords: "Tenth May Two Thousand Eleven",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "7TH (SEVENTH)",
    dateOfAdmission: "18-06-2022",
    progressInStudies: "SATISFACTORY",
    conduct: "GOOD",
    standardStudying: "STD 8TH (EIGHTH) SINCE JUNE 2023",
  },
  {
    id: 4,
    lcNo: "821",
    enrollNo: "2645",
    name: "YADAV ASHISH SURESH",
    stdFromLeave: "STD 8TH (EIGHTH) SINCE JUNE 2023",
    stdClass: "STD VIII-A",
    reasonOfLeaving: "GUARDIAN WISH",
    remark: "PASSED STD 8TH IN APRIL 2024",
    leftDate: "02-05-2024",
    issueDate: "02-05-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140025",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "821",
    generalRegisterNo: "1655",
    uidAadharCardNo: "738304278345",
    fatherName: "SURESH",
    motherName: "MEENA",
    nationality: "INDIAN",
    motherTongue: "HINDI",
    religion: "HINDU",
    caste: "OBC",
    subCaste: "",
    placeOfBirth: "PALGHAR",
    district: "PALGHAR",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "05-07-2011",
    dateOfBirthInWords: "Fifth July Two Thousand Eleven",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "7TH (SEVENTH)",
    dateOfAdmission: "22-06-2022",
    progressInStudies: "GOOD",
    conduct: "GOOD",
    standardStudying: "STD 8TH (EIGHTH) SINCE JUNE 2023",
  },
  {
    id: 5,
    lcNo: "820",
    enrollNo: "3224",
    name: "KHAN ASIF RAFIK",
    stdFromLeave: "STD. 9TH (NINTH) SINCE JUNE 2023",
    stdClass: "STD IX-A",
    reasonOfLeaving: "GUARDIAN WISH",
    remark: "PASSED STD 9TH IN APRIL 2024",
    leftDate: "02-05-2024",
    issueDate: "02-05-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140026",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "820",
    generalRegisterNo: "1656",
    uidAadharCardNo: "738304278346",
    fatherName: "RAFIK",
    motherName: "SHABNAM",
    nationality: "INDIAN",
    motherTongue: "URDU",
    religion: "MUSLIM",
    caste: "MUSLIM",
    subCaste: "",
    placeOfBirth: "MUMBAI",
    district: "MUMBAI",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "12-09-2010",
    dateOfBirthInWords: "Twelfth September Two Thousand Ten",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "8TH (EIGHTH)",
    dateOfAdmission: "25-06-2022",
    progressInStudies: "SATISFACTORY",
    conduct: "GOOD",
    standardStudying: "STD 9TH (NINTH) SINCE JUNE 2023",
  },
  {
    id: 6,
    lcNo: "819",
    enrollNo: "1398",
    name: "AHMAD NAGMA BASEER",
    stdFromLeave: "STD 8TH SINCE JUNE 2023",
    stdClass: "STD VIII-A",
    reasonOfLeaving: "GUARDIAN WISH",
    remark: "PASSESD STD 8TH IN APRIL 2024",
    leftDate: "02-05-2024",
    issueDate: "02-05-2024",
    // Additional data for certificate
    studentIdNo: "27015273611156140027",
    medium: "HINDI",
    section: "MADHYAMIK",
    serialNo: "819",
    generalRegisterNo: "1657",
    uidAadharCardNo: "738304278347",
    fatherName: "BASEER",
    motherName: "RESHMA",
    nationality: "INDIAN",
    motherTongue: "URDU",
    religion: "MUSLIM",
    caste: "MUSLIM",
    subCaste: "",
    placeOfBirth: "THANE",
    district: "THANE",
    state: "MAHARASHTRA",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "18-11-2011",
    dateOfBirthInWords: "Eighteenth November Two Thousand Eleven",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "7TH (SEVENTH)",
    dateOfAdmission: "20-06-2022",
    progressInStudies: "SATISFACTORY",
    conduct: "GOOD",
    standardStudying: "STD 8TH SINCE JUNE 2023",
  },
];
