export const leftStudents = [
  // Similar structure with additional certificate data
  {
    id: 1,
    lcNo: "712",
    enrollNo: "2245",
    name: "SHARMA PRIYA RAJESH",
    stdFromLeave: "STD 7TH (SEVENTH) SINCE JUNE 2023",
    stdClass: "STD VII-B",
    reasonOfLeaving: "FAMILY RELOCATION",
    remark: "PASSED STD 6TH IN APRIL 2023",
    leftDate: "15-07-2023",
    issueDate: "20-07-2023",
    // Additional data for certificate
    studentIdNo: "27015273611156140028",
    medium: "HINDI",
    section: "PRATHAMIK",
    serialNo: "712",
    generalRegisterNo: "1658",
    uidAadharCardNo: "738304278348",
    fatherName: "RAJESH",
    motherName: "SUNITA",
    nationality: "INDIAN",
    motherTongue: "HINDI",
    religion: "HINDU",
    caste: "GENERAL",
    subCaste: "",
    placeOfBirth: "DELHI",
    district: "DELHI",
    state: "DELHI",
    nation: "INDIA",
    taluka: "",
    dateOfBirth: "22-03-2012",
    dateOfBirthInWords: "Twenty Second March Two Thousand Twelve",
    lastSchoolAttended:
      "SHRI RAGHUBIR PRATHAMIK VIDYALAYA YADAV NAGAR, BOISAR(EAST) PALGHAR - 401501",
    lastSchoolStandard: "6TH (SIXTH)",
    dateOfAdmission: "15-06-2022",
    progressInStudies: "GOOD",
    conduct: "EXCELLENT",
    standardStudying: "STD 7TH (SEVENTH) SINCE JUNE 2023",
  },
  // Other left students...
];
